name: Deploy to GitHub Pages

on:
  push:
    branches: [ template ] # O 'master', asegúrate de que sea el nombre de tu rama principal
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # No necesitas configurar node o npm manualmente, esta acción lo hace por ti